
name   : 'Install CppUnit'
author : 'Takahiro Itou'
description : 'Install CppUnit'

inputs :
  install-prefix :
    description : 'Install Directory'
    required    : false
    default     : ${{ github.workspace }}/tools/cppunit
  version :
    description : 'Version of CppUnit'
    required    : false
    default     : '1.15.1'
  sha256sum :
    description : 'Hash of Source Package'
    required    : false
    default : 89c5c6665337f56fd2db36bc3805a5619709d51fb136e51937072f63fcc717a7

runs:
  using : "composite"
  steps :
    - name : Initialize
      run  : |
        pwd
        mkdir -p init
        ls -alR
      shell : bash

    - name : Cache Installed CppUnit
      id   : cache-installed-cppunit
      uses : actions/cache@v4
      env  :
        cache-name : cache-installed-cppunit-${{ inputs.version }}
      with :
        path : ${{ inputs.install-prefix }}
        key  : ${{ runner.os }}-${{ env.cache-name }}

    - name : Set GitHub Path
      run  : echo "${GITHUB_ACTION_PATH}" >> ${GITHUB_PATH}
      env  :
        GITHUB_ACTION_PATH : ${{ github.action_path }}
      shell : bash

    - if : ${{ steps.cache-installed-cppunit.outputs.cache-hit != 'true' }}
      name : Install CppUnit
      run  : |
        install.sh "${{ inputs.install-prefix }}" "${{ inputs.version }}"
      shell : bash

branding:
  icon  : 'check-circle'
  color : 'green'
